codes = {
    "add": 0x20,
    "addi": 0x08,
    "addiu": 0x09,
    "addu": 0x21,
    "and": 0x24,
    "andi": 0x0C,
    "beq": 0x04,
    "blez": 0x06,
    "bne": 0x05,
    "bgtz": 0x07,
    "div": 0x1A,
    "divu": 0x1B,
    "j": 0x02,
    "jal": 0x03,
    "jalr": 0x09,
    "jr": 0x08,
    "lb": 0x20,
    "lbu": 0x24,
    "lhu": 0x25,
    "lui": 0x0F,
    "lw": 0x23,
    "mfhi": 0x10,
    "mthi": 0x11,
    "mflo": 0x12,
    "mtlo": 0x13,
    "mfc0": 0x10,
    "mult": 0x18,
    "multu": 0x19,
    "nor": 0x27,
    "xor": 0x26,
    "or": 0x25,
    "ori": 0x0D,
    "sb": 0x28,
    "sh": 0x29,
    "slt": 0x2A,
    "slti": 0x0A,
    "sltiu": 0x0B,
    "sltu": 0x2B,
    "sll": 0x00,
    "srl": 0x02,
    "sra": 0x03,
    "sub": 0x22,
    "subu": 0x23,
    "sw": 0x2B
}


commandTypes = {
    "add": "R",
    "addi": "I",
    "addiu": "I",
    "addu": "R",
    "and": "R",
    "andi": "I",
    "beq": "I",
    "blez": "I",
    "bne": "I",
    "bgtz": "I",
    "div": "R",
    "divu": "R",
    "j": "J",
    "jal": "J",
    "jalr": "R",
    "jr": "R",
    "lb": "I",
    "lbu": "I",
    "lhu": "I",
    "lui": "I",
    "lw": "I",
    "mfhi": "R",
    "mthi": "R",
    "mflo": "R",
    "mtlo": "R",
    "mfc0": "R",
    "mult": "R",
    "multu": "R",
    "nor": "R",
    "xor": "R",
    "or": "R",
    "ori": "I",
    "sb": "I",
    "sh": "I",
    "slt": "R",
    "slti": "I",
    "sltiu": "I",
    "sltu": "R",
    "sll": "R",
    "srl": "R",
    "sra": "R",
    "sub": "R",
    "subu": "R",
    "sw": "I"
}

structures = {
    "R": [
        ["opcode", 6],
        ["rs", 5],
        ["rt", 5],
        ["rd", 5],
        ["shamt", 5],
        ["funct", 6]
    ],

    "I": [
        ["opcode", 6],
        ["rs", 5],
        ["rt", 5],
        ["IMM", 16]
    ],

    "J": [
        ["opcode", 6],
        ["Address", 26]
    ],
}